# Generated by Django 6.0.5 on 2026-06-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='请求时间')),
                ('ip', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='客户端IP')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, default='', max_length=1024, verbose_name='请求路径')),
                ('full_path', models.TextField(blank=True, default='', verbose_name='完整路径(含参数)')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('referer', models.TextField(blank=True, default='', verbose_name='Referer')),
                ('accept_language', models.CharField(blank=True, default='', max_length=255, verbose_name='Accept-Language')),
                ('accept_encoding', models.CharField(blank=True, default='', max_length=255, verbose_name='Accept-Encoding')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='Host')),
                ('subdomain', models.CharField(blank=True, default='', max_length=255, verbose_name='二级域名前缀')),
                ('is_spider', models.BooleanField(default=False, verbose_name='是否爬虫')),
                ('matched_spider', models.CharField(blank=True, default='', max_length=128, verbose_name='匹配的爬虫特征')),
                ('is_from_search_engine', models.BooleanField(default=False, verbose_name='是否来自搜索引擎')),
                ('matched_engine', models.CharField(blank=True, default='', max_length=128, verbose_name='匹配的搜索引擎特征')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_template', models.CharField(blank=True, default='', max_length=255, verbose_name='响应模板')),
            ],
            options={
                'verbose_name': '请求日志',
                'verbose_name_plural': '请求日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
