# Generated by Django 6.0.5 on 2026-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XingXingWeb', '0001_request_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='host',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, default='', null=True, verbose_name='客户端IP'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='is_from_search_engine',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否来自搜索引擎'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='is_spider',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否爬虫'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1024, verbose_name='请求路径'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='status_code',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='响应状态码'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='subdomain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='二级域名前缀'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['is_spider', 'is_from_search_engine', '-timestamp'], name='idx_type_time'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['ip', '-timestamp'], name='idx_ip_time'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['subdomain', '-timestamp'], name='idx_subdomain_time'),
        ),
    ]
